trigger:
- master

pool:
  name: 'MyHostPool' # Your self-hosted agent pool name

variables:
  dockerRegistryServiceConnection: 'your-docker-registry-connection' # Update this
  imageName: 'your-image-name' # Update this

stages:
- build
- push

build:
  stage: build
  displayName: 'Build and push image'
  jobs:
  - job: build
    displayName: 'Build'
    steps:
    - task: Docker@2
      displayName: 'Login to Docker Hub'
      inputs:
        command: 'login'
        containerRegistry: '$(dockerRegistryServiceConnection)'

    - task: Docker@2
      displayName: 'Build and push image'
      inputs:
        command: 'buildAndPush'
        repository: '$(imageName)'
        Dockerfile: '**/Dockerfile'
        containerRegistry: '$(dockerRegistryServiceConnection)'
        tags: '$(Build.BuildId)'